### ISSUE TITLE
Add trusted contributors to the open-cluster-management GitHub org

### ISSUE THREAD

**Issue by ray-harris** [open-cluster-management/website#8]
To facilitate community members to easily contribute to the Open Cluster Management project, we need to find a way to securely add contributors to the open-cluster-management GitHub org.

**Comment by mikeshng** [comment]
Hi Ray, sorry for the confusion but this is the website code for OCM but probably not the right place to track the issue you are describing. I have created the same issue under the https://github.com/open-cluster-management/community repo as requested by Juliana. Thanks.

```
https://github.com/open-cluster-management/community/issues/7
```
